### ISSUE TITLE
Missing last part of Splitted video (not duplicated issue)

### ISSUE THREAD

**Issue by hypercian** [SpEcHiDe/PublicLeech#33] opened 2020-04-25 17:08 UTC
Hello
I and all of the groups i seen ,have this problem

for example 1.6GB video file, splitted only 1 part

and i seen log on heroku and there is only 1 part splitted report

This is not duplicated issue because you didn't answer yet

Are you working on this problem or it is solved ?

**Comment by SpEcHiDe** [comment] 2020-04-25 17:09
Duplicate of #24 

I will push in a patch soon.

**Closed by SpEcHiDe** 2020-04-25 17:09 UTC

**Comment by hypercian** [comment] 2020-04-25 17:16
I read #24 but I didn't understand what relative is between this problem and #24 (WinRAR?!) ,but OK Thank you for answering 🌹

**Comment by SpEcHiDe** [comment] 2020-04-25 17:22
I will just write it down here. 

What I am doing in the split_file is taking the total duration and cutting it by 1 / n th of the duration so that file size gets reduced. but, for some videos with different encodings this technique fails because of the FFMpeg version that is being used by the bot server. 

so, #24 is the correct method (I think) which would get the actual leeched file without any quality difference. 

Feel free to comment in #24,  😁😁☺️

**Comment by hypercian** [comment] 2020-04-25 17:35
OK I understand
Thank you for good Description 👍
