### ISSUE TITLE
Could You Please Add Renaming Feature?

### ISSUE THREAD

**Issue by JyothisJayanth** [SpEcHiDe/PublicLeech#48] opened 2020-05-27 11:40 UTC
This Public Leech is Awesome. Could You Please Add Renaming Feature.

**Comment by SpEcHiDe** [comment] 2020-05-27 11:41
Duplicate of #15

**Closed by SpEcHiDe** 2020-05-27 11:41 UTC

**Comment by theRay1s** [comment] 2020-05-29 02:47
@JyothisJayanth it's already there
